import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f8fafc' },
  header: { backgroundColor: '#4F46E5', padding: 20, paddingBottom: 30 },
  headerTitle: { fontSize: 24, fontWeight: 'bold', color: '#fff', marginBottom: 5 },
  headerSubtitle: { fontSize: 14, color: '#E0E7FF' },
  content: { flex: 1, padding: 16 },
  statsContainer: { marginBottom: 24 },
  statCard: { padding: 16, borderRadius: 12, marginBottom: 12, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  statTitle: { fontSize: 18, fontWeight: '600' },
  statAmount: { fontSize: 24, fontWeight: 'bold' },
  editBalanceText: { fontSize: 12, color: '#6366f1', marginTop: 2 },
  actionButtonsContainer: { flexDirection: 'row', marginBottom: 24, gap: 12 },
  actionButton: { flex: 1, backgroundColor: '#6366F1', padding: 12, borderRadius: 8, alignItems: 'center' },
  actionButtonText: { color: '#fff', fontWeight: '600' },
  transactionsContainer: { backgroundColor: '#fff', borderRadius: 12, padding: 16, marginBottom: 16 },
  recurringContainer: { backgroundColor: '#f0f9ff', borderRadius: 12, padding: 16 },
  sectionTitle: { fontSize: 18, fontWeight: '600', marginBottom: 16, color: '#1f2937' },
  emptyText: { textAlign: 'center', color: '#6b7280', fontStyle: 'italic', padding: 20 },
  emptySubtext: { textAlign: 'center', color: '#9ca3af', fontSize: 14, marginTop: 8 },
  transactionItem: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 12, paddingHorizontal: 16, backgroundColor: '#f9fafb', borderRadius: 8, marginBottom: 8 },
  transactionInfo: { flex: 1 },
  transactionDescription: { fontSize: 16, fontWeight: '600', color: '#1f2937', marginBottom: 4 },
  transactionDetails: { fontSize: 14, color: '#6b7280' },
  transactionAmount: { fontSize: 16, fontWeight: 'bold' },
  recurringItem: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 12, paddingHorizontal: 16, backgroundColor: '#e0f2fe', borderRadius: 8, marginBottom: 8 },
  recurringDescription: { fontSize: 16, fontWeight: '600', color: '#0369a1' },
  recurringDetails: { fontSize: 14, color: '#0284c7' },
  recurringBadge: { fontSize: 12, backgroundColor: '#0ea5e9', color: '#fff', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 12 },
  formContainer: { flex: 1, backgroundColor: '#fff', borderRadius: 12, padding: 20 },
  formTitle: { fontSize: 20, fontWeight: '600', marginBottom: 20, color: '#1f2937' },
  scanButton: { backgroundColor: '#10b981', padding: 16, borderRadius: 8, alignItems: 'center', marginBottom: 20 },
  scanButtonDisabled: { backgroundColor: '#9ca3af' },
  scanButtonText: { color: '#fff', fontSize: 16, fontWeight: '600' },
  processingIndicator: { backgroundColor: '#f0f9ff', padding: 16, borderRadius: 8, alignItems: 'center', marginBottom: 20 },
  processingText: { fontSize: 16, fontWeight: '600', color: '#0369a1', marginBottom: 4 },
  processingSubtext: { fontSize: 12, color: '#0284c7', marginBottom: 2 },
  typeContainer: { flexDirection: 'row', marginBottom: 20, gap: 12 },
  typeButton: { flex: 1, padding: 16, borderRadius: 8, borderWidth: 2, borderColor: '#e5e7eb', alignItems: 'center' },
  typeText: { fontSize: 16, fontWeight: '600' },
  expenseActive: { borderColor: '#dc2626', backgroundColor: '#fee2e2' },
  incomeActive: { borderColor: '#16a34a', backgroundColor: '#dcfce7' },
  recurringToggle: { padding: 16, borderRadius: 8, borderWidth: 2, borderColor: '#e5e7eb', alignItems: 'center', marginBottom: 20 },
  recurringToggleActive: { borderColor: '#0ea5e9', backgroundColor: '#e0f2fe' },
  recurringToggleText: { fontSize: 16, fontWeight: '600' },
  frequencyContainer: { marginBottom: 20 },
  label: { fontSize: 16, fontWeight: '600', marginBottom: 8, color: '#1f2937' },
  frequencyButtons: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  frequencyButton: { paddingHorizontal: 16, paddingVertical: 8, borderRadius: 20, borderWidth: 1, borderColor: '#d1d5db' },
  frequencyButtonActive: { backgroundColor: '#3b82f6', borderColor: '#3b82f6' },
  frequencyButtonText: { fontSize: 14, color: '#6b7280' },
  frequencyButtonTextActive: { color: '#fff' },
  categoryContainer: { marginBottom: 20 },
  categoryScroll: { marginTop: 8 },
  categoryButton: { paddingHorizontal: 16, paddingVertical: 8, borderRadius: 20, borderWidth: 1, borderColor: '#d1d5db', marginRight: 8 },
  categoryButtonActive: { backgroundColor: '#4f46e5', borderColor: '#4f46e5' },
  categoryButtonText: { fontSize: 14, color: '#6b7280' },
  categoryButtonTextActive: { color: '#fff' },
  input: { borderWidth: 1, borderColor: '#d1d5db', borderRadius: 8, padding: 12, fontSize: 16, marginBottom: 16, backgroundColor: '#fff' },
  addButton: { backgroundColor: '#4F46E5', padding: 16, borderRadius: 8, alignItems: 'center' },
  addButtonText: { color: '#fff', fontSize: 16, fontWeight: '600' },
  tabContainer: { flexDirection: 'row', backgroundColor: '#fff', paddingVertical: 10, paddingHorizontal: 16, borderTopWidth: 1, borderTopColor: '#e5e7eb' },
  tabButton: { flex: 1, alignItems: 'center', paddingVertical: 8, paddingHorizontal: 12, marginHorizontal: 4, borderRadius: 8, backgroundColor: '#f5f5f5' },
  activeTab: { backgroundColor: '#4F46E5' },
  tabLabel: { fontSize: 14, color: '#666' },
  activeTabLabel: { color: '#fff' },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'center', alignItems: 'center' },
  modalContent: { backgroundColor: '#fff', padding: 20, borderRadius: 12, margin: 20, minWidth: 300 },
  modalTitle: { fontSize: 18, fontWeight: 'bold', marginBottom: 10, textAlign: 'center' },
  modalText: { fontSize: 16, marginBottom: 20, textAlign: 'center', color: '#6b7280' },
  modalButtons: { flexDirection: 'row', gap: 12 },
  modalButton: { flex: 1, padding: 12, borderRadius: 8, alignItems: 'center', borderWidth: 1, borderColor: '#d1d5db' },
  deleteButton: { backgroundColor: '#dc2626', borderColor: '#dc2626' },
  confirmButton: { backgroundColor: '#10b981', borderColor: '#10b981' },
  modalButtonText: { fontSize: 16, fontWeight: '600', color: '#6b7280' },
  deleteButtonText: { color: '#fff' },
  confirmButtonText: { color: '#fff' },
  balanceInput: { borderWidth: 1, borderColor: '#d1d5db', borderRadius: 8, padding: 12, fontSize: 18, marginBottom: 20, textAlign: 'center' },
  modalContainer: { flex: 1, backgroundColor: '#f8fafc' },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 20, backgroundColor: '#4F46E5' },
  modalHeaderTitle: { fontSize: 20, fontWeight: 'bold', color: '#fff' },
  closeButton: { fontSize: 24, color: '#fff', fontWeight: 'bold' },
  receiptsContainer: { flex: 1, padding: 16 },
  emptyReceiptsContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 40 },
  receiptItem: { flexDirection: 'row', backgroundColor: '#fff', padding: 16, borderRadius: 12, marginBottom: 12, position: 'relative', elevation: 2, shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4 },
  receiptImage: { width: 80, height: 80, borderRadius: 8, marginRight: 16 },
  receiptInfo: { flex: 1 },
  receiptMerchant: { fontSize: 16, fontWeight: '600', color: '#1f2937' },
  receiptAmount: { fontSize: 16, fontWeight: 'bold', color: '#dc2626', marginVertical: 2 },
  receiptItems: { fontSize: 12, color: '#6366f1', marginBottom: 2 },
  receiptEngine: { fontSize: 12, color: '#059669', marginBottom: 2 },
  receiptConfidence: { fontSize: 11, color: '#0284c7', marginBottom: 2 },
  receiptDate: { fontSize: 12, color: '#6b7280', marginBottom: 2 },
  receiptTapHint: { fontSize: 11, color: '#059669', fontStyle: 'italic' },
  receiptBadge: { position: 'absolute', top: 8, right: 8, backgroundColor: '#10b981', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 12 },
  receiptBadgeText: { fontSize: 10, color: '#fff', fontWeight: '600' },
  reportsContainer: { flex: 1, padding: 16 },
  pieChartContainer: { backgroundColor: '#fff', padding: 20, borderRadius: 12, marginBottom: 16 },
  chartTitle: { fontSize: 18, fontWeight: '600', marginBottom: 16, textAlign: 'center', color: '#1f2937' },
  chartItem: { flexDirection: 'row', alignItems: 'center', marginBottom: 8 },
  colorIndicator: { width: 16, height: 16, borderRadius: 8, marginRight: 12 },
  chartLabel: { fontSize: 14, color: '#4b5563' },
  summaryContainer: { backgroundColor: '#fff', padding: 20, borderRadius: 12 },
  summaryTitle: { fontSize: 18, fontWeight: '600', marginBottom: 16, textAlign: 'center', color: '#1f2937' },
  summaryRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 8 },
  summaryRowFinal: { borderTopWidth: 2, borderTopColor: '#e5e7eb', marginTop: 8, paddingTop: 16 },
  summaryLabel: { fontSize: 16, color: '#6b7280' },
  summaryValue: { fontSize: 16, fontWeight: '600', color: '#1f2937' },
  summaryLabelFinal: { fontSize: 18, fontWeight: '600', color: '#1f2937' },
  summaryValueFinal: { fontSize: 20, fontWeight: 'bold' },
  itemsContainer: { flex: 1, padding: 16 },
  instructionText: { fontSize: 16, fontWeight: '600', marginBottom: 16, color: '#1f2937', textAlign: 'center' },
  itemCard: { flexDirection: 'row', backgroundColor: '#fff', padding: 16, borderRadius: 12, marginBottom: 12, borderWidth: 2, borderColor: '#e5e7eb', alignItems: 'center' },
  itemCardSelected: { borderColor: '#10b981', backgroundColor: '#f0fdf4' },
  itemInfo: { flex: 1 },
  itemDescription: { fontSize: 16, fontWeight: '600', color: '#1f2937', marginBottom: 4 },
  itemCategory: { fontSize: 14, color: '#6b7280', marginBottom: 2 },
  itemLineNumber: { fontSize: 12, color: '#9ca3af', marginBottom: 2 },
  itemConfidence: { fontSize: 12, color: '#059669' },
  itemAmountContainer: { alignItems: 'center' },
  itemAmount: { fontSize: 18, fontWeight: 'bold', color: '#dc2626', marginBottom: 4 },
  checkMark: { fontSize: 20, color: '#10b981', fontWeight: 'bold' },
  multipleItemsActions: { padding: 16, backgroundColor: '#fff', borderTopWidth: 1, borderTopColor: '#e5e7eb' },
  addSelectedButton: { backgroundColor: '#10b981', padding: 16, borderRadius: 8, alignItems: 'center' },
  addSelectedButtonText: { color: '#fff', fontSize: 16, fontWeight: '600' },
  settingsContainer: { flex: 1, padding: 16 },
  settingsTitle: { fontSize: 20, fontWeight: '600', marginBottom: 8, color: '#1f2937', textAlign: 'center' },
  settingsSubtitle: { fontSize: 14, color: '#6b7280', marginBottom: 24, textAlign: 'center' },
  settingOption: { backgroundColor: '#fff', padding: 20, borderRadius: 12, marginBottom: 16, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  settingInfo: { flex: 1 },
  settingName: { fontSize: 16, fontWeight: '600', color: '#1f2937', marginBottom: 4 },
  settingDescription: { fontSize: 14, color: '#6b7280' },
  settingToggle: { backgroundColor: '#e5e7eb', paddingHorizontal: 16, paddingVertical: 8, borderRadius: 20 },
  settingToggleActive: { backgroundColor: '#10b981' },
  settingToggleText: { fontSize: 14, fontWeight: '600', color: '#6b7280' },
  settingSlider: { backgroundColor: '#fff', padding: 20, borderRadius: 12, marginBottom: 16 },
  sliderContainer: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 12 },
  sliderOption: { backgroundColor: '#e5e7eb', paddingHorizontal: 12, paddingVertical: 8, borderRadius: 20 },
  sliderOptionActive: { backgroundColor: '#6366f1' },
  sliderText: { fontSize: 12, fontWeight: '600', color: '#6b7280' },
  debugInfoContainer: { backgroundColor: '#fef3c7', padding: 16, borderRadius: 12, marginBottom: 16 },
  debugTitle: { fontSize: 16, fontWeight: '600', color: '#92400e', marginBottom: 8 },
  debugText: { fontSize: 14, color: '#92400e', marginBottom: 4 },
  ocrTipsContainer: { backgroundColor: '#fffbeb', padding: 20, borderRadius: 12 },
  tipsTitle: { fontSize: 16, fontWeight: '600', color: '#92400e', marginBottom: 12 },
  tipText: { fontSize: 14, color: '#92400e', marginBottom: 6 },
  receiptDetailContainer: { flex: 1, padding: 16 },
  receiptImageContainer: { backgroundColor: '#fff', padding: 16, borderRadius: 12, marginBottom: 16, alignItems: 'center' },
  receiptDetailImage: { width: width - 64, height: (width - 64) * 1.3, borderRadius: 8, resizeMode: 'contain' },
  receiptInfoSection: { backgroundColor: '#fff', padding: 16, borderRadius: 12, marginBottom: 16 },
  infoRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 6, borderBottomWidth: 1, borderBottomColor: '#f3f4f6' },
  infoLabel: { fontSize: 14, color: '#6b7280', fontWeight: '500' },
  infoValue: { fontSize: 14, color: '#1f2937', fontWeight: '600' },
  processingStep: { fontSize: 14, color: '#059669', marginBottom: 4, paddingLeft: 8 },
  detectedItem: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 12, paddingHorizontal: 16, backgroundColor: '#f0fdf4', borderRadius: 8, marginBottom: 8 },
  itemDetailInfo: { flex: 1 },
  itemDetailDescription: { fontSize: 15, fontWeight: '600', color: '#065f46', marginBottom: 2 },
  itemDetailCategory: { fontSize: 13, color: '#047857', marginBottom: 2 },
  itemDetailLine: { fontSize: 12, color: '#059669', marginBottom: 2 },
  itemDetailConfidence: { fontSize: 12, color: '#0d9488' },
  itemDetailAmount: { fontSize: 16, fontWeight: 'bold', color: '#dc2626' },
  potentialItem: { paddingVertical: 8, paddingHorizontal: 12, backgroundColor: '#fef3c7', borderRadius: 6, marginBottom: 6, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  potentialItemText: { fontSize: 13, color: '#92400e', flex: 1 },
  potentialItemScore: { fontSize: 11, color: '#f59e0b', fontWeight: '600' },
  potentialItemsNote: { fontSize: 13, color: '#92400e', marginBottom: 12, fontStyle: 'italic' },
  moreItemsText: { fontSize: 13, color: '#6b7280', textAlign: 'center', marginTop: 8, fontStyle: 'italic' },
  rawTextContainer: { backgroundColor: '#f8fafc', padding: 16, borderRadius: 8, maxHeight: 200 },
  rawText: { fontSize: 11, color: '#4b5563', lineHeight: 16 },

  viewTabsContainer: {
    flexDirection: 'row',
    marginBottom: 16,
    backgroundColor: '#f3f4f6',
    borderRadius: 8,
    padding: 4,
  },
  viewTab: {
    flex: 1,
    paddingVertical: 8,
    alignItems: 'center',
    borderRadius: 6,
  },
  viewTabActive: {
    backgroundColor: '#fff',
    elevation: 1,
    shadowOpacity: 0.1,
    shadowRadius: 3,
  },
  viewTabText: {
    fontWeight: '600',
    color: '#6b7280',
  },
  viewTabTextActive: {
    color: '#4f46e5',
  },
  categorySummaryItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#f3f4f6',
  },
  categorySummaryText: {
    fontSize: 16,
    color: '#374151',
  },
  categorySummaryAmount: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1f2937',
  },
});
